data:
  class_path: anomalib.data.Folder
  init_args:
    root: ../data/VCTIM/
    normal_dir: "train/good"          
    abnormal_dir: "test/bad"      
    image_size: 256
    center_crop: null
    normalization: imagenet
    train_batch_size: 72
    eval_batch_size: 32
    num_workers: 8
    task: classification
    test_split_mode: from_dir
    test_split_ratio: 0.2
    val_split_mode: same_as_test
    val_split_ratio: 0.5
    seed: 42
    augmentations:
      class_path: torchvision.transforms.v2.Compose
      init_args:
        transforms:
          - class_path: torchvision.transforms.v2.Resize
            init_args:
              size: [256, 256]
          - class_path: torchvision.transforms.v2.CenterCrop
            init_args:
              size: [256, 256]
          - class_path: torchvision.transforms.v2.ToDtype
            init_args:
              dtype: torch.float32
              scale: true
          - class_path: torchvision.transforms.v2.Normalize
            init_args:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]

model:
  class_path: anomalib.models.Patchcore
  init_args:
    backbone: wide_resnet50_2
    pre_trained: true
    layers:
      - layer2
      - layer3
    coreset_sampling_ratio: 0.1
    num_neighbors: 9

normalization:
  normalization_method: min_max

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    class_path: anomalib.metrics.F1AdaptiveThreshold
    init_args:
      default_value: 0.5