services:
  inspector:
    build: .
    ports:
      - "8501:8501"
    devices:
      - "/dev/video0:/dev/video0" # Maps the first USB camera to the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1